global:
  scrape_interval: 5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.
  scrape_timeout: 3s # Timeout scrape after 3 seconds. The default is every 10 seconds.

scrape_configs:
  - job_name: "athena-trace-metrics"
    static_configs:
      - targets: [ 'athena-jaeger:8889' ]

otlp:
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - cloud.availability_zone
    - cloud.region
    - container.name
    - deployment.environment.name

storage:
  tsdb:
    out_of_order_time_window: 30m
